#ifndef __LPARAM_CONSTANTS
#define __LPARAM_CONSTANTS
#define NEWPREDICATEPREFIX "NSM"
#define CLUSTERFILE "cluster.cls"
#define RESULTFILE "result.dat"
#define MAXTIMEOUTCLUSTERING 60
#define PROPOSALNUMPARENTS 2
#define SPLITCHUNKSIZE 25
#define PRINTRESULTSINTERVAL 25
#define CLUSTERINGWINDOWSIZE 100
//parameters for  inference
#define PROPOSALUPDATEINTERVAL 50
#define MAXSTEPSINFER 1000
#define MAXSTEPSWL 20
#define MAXSECONDSWL 120
#define MAXSECONDSINFER 10000
#define BURNINSTEPS 50
#define LEARNINGRATE 0.001
#define SLEEPTIME 5
//caching in PTP exact inference
#define CACHESIZE 1024
#define MOSTRECENTSIZE 50
#define MAXCNFSIZE 256
#endif
